### PR TITLE
Fixed issue #16  and #17 

### PR DESCRIPTION
**Pull request by jerrychee94**
Dear author, this pull request is related to issue https://github.com/nrml-co/nova-big-filter/issues/16 and https://github.com/nrml-co/nova-big-filter/issues/17.

Commit:
1) Please run npm install to install all the required libraries.
2) Unlike the default laravel nova filter, $emit('filter-changed') and $emit('clear-selected-filters') will not
work for this case because there's no event listener for these 2 events.
Thus, we will need to import laravel nova library and call the method
directly.

### CODE REVIEW

**Comment by Jun-ocx** [comment]
Thank you Jerry,

What I've done so far,
1. Downloaded from fix/reset-button-and-pagination-reset branch and placed in default laravel/nova root folder in order to install it via composer in composer.json.

2. Ran npm install and composer update.

3. Applied nova-big-filter into User tab by seeding 50 users using userFactory and registered UserType filter along with it.

4. Issue #17 (saving filtered history in URL) seemed to be solved but not #16 (reset pagination after the filter value is changed).

5. 'Reset Filter' button only appeared in original nova filter but not in 'nova-big-filter' field. Also, when the filter value is changed, the pagination is not reset

Please correct me if there is a misguidance.

**Comment by jerrychee94** [comment]
Hi Jun,

I believe that you are still using the original ones (without my changes). The original code was disabled/commented by author [see here](https://github.com/nrml-co/nova-big-filter/blob/a90889ff82e970a3c84ef3dc70ddd4df5f6c1d09/resources/js/components/Card.vue#L12). In my PR, I enabled the reset button and made it working.

Note: You should never place anything it in default laravel/nova root folder.

This is how i think you should do, 
1)Revert back all the changes that you've made in your comment.
2) run `composer require composer require nrml-co/nova-big-filter:fix/reset-button-and-pagination-reset`

If it is working, you should be able to see 'reset filter' in the bottom of the big filter card. (Sorry I cannot show the actual picture of my project)
image

**Comment by jerrychee94** [comment]
Hi @edanisko, 

Any chance of reviewing this pull request ? I hope this pull request can be merged.

**Comment by Jun-ocx** [comment]
Thank you Jerry,

I just found out that the reason why it didn't work out, was because your changes were not built (were missing) in 'dist' file. 
However, after run 'npm run prod' in /vendor/nrml-co/nova-big-filter, the button and reset work properly.
So, I recommend you to commit **the final version with completely built dist file**,
or if you haven't done **'npm run prod'** in your local, please do and commit&pull request so that the author can merge your PR.

**Comment by jerrychee94** [comment]
Hi Jun,

I actually did commit the one with npm run prod. `https://github.com/nrml-co/nova-big-filter/pull/18/commits/eebdad95b48001d96e0aef80d26f02315c000872`

**Comment by Jun-ocx** [comment]
Hi Jerry,

I can see the file has changes but it seemed not "up-to-date" because "reset filter" keyword in dist is not searchable in that file whereas my npm run prod dist has it.

**Pull request merged**
